import 'package:flutter/widgets.dart';
import 'package:prime_flutter/prime_flutter.dart';

class IconsScreen extends StatelessWidget {
  const IconsScreen({super.key});

  static final List<MapEntry<String, IconData>> _allIcons = [
    const MapEntry('checkboxIndeterminate', PrimeIcons.checkboxIndeterminate),
    const MapEntry('cursorMove', PrimeIcons.cursorMove),
    const MapEntry('gridOrthographic', PrimeIcons.gridOrthographic),
    const MapEntry('gridPerspective', PrimeIcons.gridPerspective),
    const MapEntry('magnetOff', PrimeIcons.magnetOff),
    const MapEntry('magnet', PrimeIcons.magnet),
    const MapEntry('maintenance', PrimeIcons.maintenance),
    const MapEntry('resize', PrimeIcons.resize),
    const MapEntry('viamComponent', PrimeIcons.viamComponent),
    const MapEntry('viamFlutter', PrimeIcons.viamFlutter),
    const MapEntry('viamFragment', PrimeIcons.viamFragment),
    const MapEntry('viamLocalModule', PrimeIcons.viamLocalModule),
    const MapEntry('viamMixedPartStatus', PrimeIcons.viamMixedPartStatus),
    const MapEntry('viamMlModel', PrimeIcons.viamMlModel),
    const MapEntry('viamRemotePart', PrimeIcons.viamRemotePart),
    const MapEntry('viamRegistryModule', PrimeIcons.viamRegistryModule),
    const MapEntry('viamService', PrimeIcons.viamService),
    const MapEntry('viamProcess', PrimeIcons.viamProcess),
    const MapEntry('accountGroupOutline', PrimeIcons.accountGroupOutline),
    const MapEntry('accountMultiple', PrimeIcons.accountMultiple),
    const MapEntry('alertCircleOutline', PrimeIcons.alertCircleOutline),
    const MapEntry('alertCircle', PrimeIcons.alertCircle),
    const MapEntry('alertOutline', PrimeIcons.alertOutline),
    const MapEntry('alert', PrimeIcons.alert),
    const MapEntry('appleKeyboardCommand', PrimeIcons.appleKeyboardCommand),
    const MapEntry('apple', PrimeIcons.apple),
    const MapEntry('applicationOutline', PrimeIcons.applicationOutline),
    const MapEntry('arrowCollapseLeft', PrimeIcons.arrowCollapseLeft),
    const MapEntry('arrowCollapseRight', PrimeIcons.arrowCollapseRight),
    const MapEntry('arrowCollapse', PrimeIcons.arrowCollapse),
    const MapEntry('arrowExpandAll', PrimeIcons.arrowExpandAll),
    const MapEntry('arrowExpandLeft', PrimeIcons.arrowExpandLeft),
    const MapEntry('arrowExpandRight', PrimeIcons.arrowExpandRight),
    const MapEntry('arrowLeft', PrimeIcons.arrowLeft),
    const MapEntry('arrowRight', PrimeIcons.arrowRight),
    const MapEntry('arrowTopRightBottomLeft', PrimeIcons.arrowTopRightBottomLeft),
    const MapEntry('arrowUp', PrimeIcons.arrowUp),
    const MapEntry('article', PrimeIcons.article),
    const MapEntry('axisArrow', PrimeIcons.axisArrow),
    const MapEntry('backupRestore', PrimeIcons.backupRestore),
    const MapEntry('broadcastOff', PrimeIcons.broadcastOff),
    const MapEntry('broadcast', PrimeIcons.broadcast),
    const MapEntry('bugOutline', PrimeIcons.bugOutline),
    const MapEntry('bug', PrimeIcons.bug),
    const MapEntry('cameraFlipOutline', PrimeIcons.cameraFlipOutline),
    const MapEntry('cameraOutline', PrimeIcons.cameraOutline),
    const MapEntry('cancel', PrimeIcons.cancel),
    const MapEntry('cardTextOutline', PrimeIcons.cardTextOutline),
    const MapEntry('chartLine', PrimeIcons.chartLine),
    const MapEntry('checkCircle', PrimeIcons.checkCircle),
    const MapEntry('check', PrimeIcons.check),
    const MapEntry('checkboxMarked', PrimeIcons.checkboxMarked),
    const MapEntry('chevronDoubleUp', PrimeIcons.chevronDoubleUp),
    const MapEntry('chevronDown', PrimeIcons.chevronDown),
    const MapEntry('chevronLeft', PrimeIcons.chevronLeft),
    const MapEntry('chevronRight', PrimeIcons.chevronRight),
    const MapEntry('chevronUp', PrimeIcons.chevronUp),
    const MapEntry('circleMd', PrimeIcons.circleMd),
    const MapEntry('clockOutline', PrimeIcons.clockOutline),
    const MapEntry('close', PrimeIcons.close),
    const MapEntry('codeBraces', PrimeIcons.codeBraces),
    const MapEntry('codeJson', PrimeIcons.codeJson),
    const MapEntry('cog', PrimeIcons.cog),
    const MapEntry('console', PrimeIcons.console),
    const MapEntry('contentCopy', PrimeIcons.contentCopy),
    const MapEntry('contentDuplicate', PrimeIcons.contentDuplicate),
    const MapEntry('contentSaveOutline', PrimeIcons.contentSaveOutline),
    const MapEntry('creditCardOutline', PrimeIcons.creditCardOutline),
    const MapEntry('databaseOutline', PrimeIcons.databaseOutline),
    const MapEntry('domain', PrimeIcons.domain),
    const MapEntry('dotsHorizontal', PrimeIcons.dotsHorizontal),
    const MapEntry('download', PrimeIcons.download),
    const MapEntry('drag', PrimeIcons.drag),
    const MapEntry('earth', PrimeIcons.earth),
    const MapEntry('exportIcon', PrimeIcons.exportIcon),
    const MapEntry('fileChartOutline', PrimeIcons.fileChartOutline),
    const MapEntry('fileDownloadOutline', PrimeIcons.fileDownloadOutline),
    const MapEntry('fileSwapOutline', PrimeIcons.fileSwapOutline),
    const MapEntry('filterOutline', PrimeIcons.filterOutline),
    const MapEntry('gamepad', PrimeIcons.gamepad),
    const MapEntry('github', PrimeIcons.github),
    const MapEntry('helpCircleOutline', PrimeIcons.helpCircleOutline),
    const MapEntry('history', PrimeIcons.history),
    const MapEntry('imageFilterCenterFocus', PrimeIcons.imageFilterCenterFocus),
    const MapEntry('informationOutline', PrimeIcons.informationOutline),
    const MapEntry('information', PrimeIcons.information),
    const MapEntry('instagram', PrimeIcons.instagram),
    const MapEntry('lanConnect', PrimeIcons.lanConnect),
    const MapEntry('languageCpp', PrimeIcons.languageCpp),
    const MapEntry('languageGo', PrimeIcons.languageGo),
    const MapEntry('languagePython', PrimeIcons.languagePython),
    const MapEntry('languageTypescript', PrimeIcons.languageTypescript),
    const MapEntry('layersTripleOutline', PrimeIcons.layersTripleOutline),
    const MapEntry('linkVariant', PrimeIcons.linkVariant),
    const MapEntry('link', PrimeIcons.link),
    const MapEntry('linkedin', PrimeIcons.linkedin),
    const MapEntry('linux', PrimeIcons.linux),
    const MapEntry('lock', PrimeIcons.lock),
    const MapEntry('logout', PrimeIcons.logout),
    const MapEntry('magnify', PrimeIcons.magnify),
    const MapEntry('menu', PrimeIcons.menu),
    const MapEntry('minus', PrimeIcons.minus),
    const MapEntry('monitorDashboard', PrimeIcons.monitorDashboard),
    const MapEntry('multiplicationBox', PrimeIcons.multiplicationBox),
    const MapEntry('navigationVariantOutline', PrimeIcons.navigationVariantOutline),
    const MapEntry('navigationVariant', PrimeIcons.navigationVariant),
    const MapEntry('networkOutline', PrimeIcons.networkOutline),
    const MapEntry('openInNew', PrimeIcons.openInNew),
    const MapEntry('packageVariantClosed', PrimeIcons.packageVariantClosed),
    const MapEntry('pauseCircleOutline', PrimeIcons.pauseCircleOutline),
    const MapEntry('pause', PrimeIcons.pause),
    const MapEntry('pencilOutline', PrimeIcons.pencilOutline),
    const MapEntry('pictureInPictureTopRight', PrimeIcons.pictureInPictureTopRight),
    const MapEntry('playCircleOutline', PrimeIcons.playCircleOutline),
    const MapEntry('plus', PrimeIcons.plus),
    const MapEntry('radioboxBlank', PrimeIcons.radioboxBlank),
    const MapEntry('radioboxIndeterminateVariant', PrimeIcons.radioboxIndeterminateVariant),
    const MapEntry('radioboxMarked', PrimeIcons.radioboxMarked),
    const MapEntry('refresh', PrimeIcons.refresh),
    const MapEntry('robotOutline', PrimeIcons.robotOutline),
    const MapEntry('scriptTextOutline', PrimeIcons.scriptTextOutline),
    const MapEntry('selectionDrag', PrimeIcons.selectionDrag),
    const MapEntry('selectionEllipse', PrimeIcons.selectionEllipse),
    const MapEntry('send', PrimeIcons.send),
    const MapEntry('shieldKeyOutline', PrimeIcons.shieldKeyOutline),
    const MapEntry('stopCircleOutline', PrimeIcons.stopCircleOutline),
    const MapEntry('syncIcon', PrimeIcons.syncIcon),
    const MapEntry('table', PrimeIcons.table),
    const MapEntry('tagOutline', PrimeIcons.tagOutline),
    const MapEntry('textSearch', PrimeIcons.textSearch),
    const MapEntry('toggleSwitchOffOutline', PrimeIcons.toggleSwitchOffOutline),
    const MapEntry('toggleSwitchOff', PrimeIcons.toggleSwitchOff),
    const MapEntry('toggleSwitchOutline', PrimeIcons.toggleSwitchOutline),
    const MapEntry('toggleSwitch', PrimeIcons.toggleSwitch),
    const MapEntry('tools', PrimeIcons.tools),
    const MapEntry('trashCanOutline', PrimeIcons.trashCanOutline),
    const MapEntry('twitter', PrimeIcons.twitter),
    const MapEntry('undo', PrimeIcons.undo),
    const MapEntry('unfoldLessHorizontal', PrimeIcons.unfoldLessHorizontal),
    const MapEntry('unfoldMoreHorizontal', PrimeIcons.unfoldMoreHorizontal),
    const MapEntry('upload', PrimeIcons.upload),
    const MapEntry('videoOutline', PrimeIcons.videoOutline),
    const MapEntry('viewDashboardOutline', PrimeIcons.viewDashboardOutline),
    const MapEntry('webhook', PrimeIcons.webhook),
    const MapEntry('windows', PrimeIcons.windows),
  ];

  @override
  Widget build(BuildContext context) {
    return PrimeScaffold(
      body: Column(
        children: [
          // Header with back button
          Container(
            padding: const EdgeInsets.all(16),
            decoration: const BoxDecoration(
              border: Border(bottom: BorderSide(color: Color(0xFFE0E0E0), width: 1)),
            ),
            child: Row(
              children: [
                GestureDetector(
                  onTap: () => Navigator.of(context).pop(),
                  child: const Row(
                    children: [
                      Icon(PrimeIcons.chevronLeft, size: 20),
                      SizedBox(width: 4),
                      Text('Back', style: TextStyle(fontSize: 16)),
                    ],
                  ),
                ),
                const SizedBox(width: 16),
                const Text('Icons', style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
              ],
            ),
          ),
          // Content
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Wrap(
                spacing: 16,
                runSpacing: 16,
                children: _allIcons.map((entry) {
                  return SizedBox(
                    width: 80,
                    child: Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Icon(entry.value, size: 32),
                        const SizedBox(height: 4),
                        Text(
                          entry.key,
                          style: const TextStyle(fontSize: 10),
                          textAlign: TextAlign.center,
                          maxLines: 2,
                          overflow: TextOverflow.ellipsis,
                        ),
                      ],
                    ),
                  );
                }).toList(),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
